name: 'GS64 Components Loading'
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
   component-loading:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        load-spec:
          - Deployment
    name: GS64 + ${{ matrix.load-spec }}
    steps:
      - uses: actions/checkout@v3
      - name: Load component in image
        uses: ba-st-actions/gs64-ci@release-candidate
        with:
          project_name: 'Aconcagua'
          load_spec: 'Aconcagua-${{ matrix.load-spec }}'
